language:
- objective-c
env:
  global:
  - LATEST_TAG=1 # comment out to build version in submodule
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag markupsafe; fi
  - cd markupsafe
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..
script:
  # install dependencies for tests e.g - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  # Run the tests
  - cd ..
before_deploy: cd markupsafe/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "fzoQ/4tEcwpq5Spc/qaGifvCm3JND0QMU5WeygGnwOLyoaVzrs8bO7qXMB1X4xOT2EiSuNbCxGRBtnd7A3+SJm7LRrwHOfcxMKk3rOVnBwTqWGvzdFckTz0sMod2/DBwPFhGgjbQ2Kcw7iUwajdSq+2i4GL133zFUSzTNwUMuEw="
  region: ORD
  container: wheels
  skip_cleanup: true
