language:
- objective-c
env:
  global:
  - LATEST_TAG=1 # comment out to build version in submodule
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag markupsafe; fi
  - cd markupsafe
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests markupsafe
  - cd ..
before_deploy: cd markupsafe/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "u9oP0NAlV9qmx6nzqAunQIEvbER8SoRdcp07mvMdcgWUzM76eHBJmORVJIQSvZAzwZLUaTmLSEXiZBek6VF9tKwvmhDkSQii8O7Ps3ZEXBQCNCCg9/AGHt3sO7Ft6AGR7mGQWX0I45P5NliU7L6xzqT5LJ3YybxkenhPeoYxjFY="
  region: ORD
  container: wheels
  skip_cleanup: true
